M48
; DRILL file {KiCad (5.99.0-11031-gb4f5b6ef3c)} date Tuesday, June 15, 2021 at 08:59:58 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-06-15T20:59:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-11031-gb4f5b6ef3c)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X3.6632Y-4.5079
X3.6632Y-4.626
X5.3819Y-4.9982
X5.5Y-4.9982
T0
M30
